before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
  - tar xzvf hugo_0.48_Linux-64bit.tar.gz
  - sudo mv hugo /usr/local/bin/
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  - hugo version
  - jq --version
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then export HUGO_ENV=production; fi

script:
  - env
  - if [[ $HUGO_ENV != "production" ]]; then hugo --buildFuture -b "http://laps.run-preview.s3-website-us-east-1.amazonaws.com/$TRAVIS_PULL_REQUEST_BRANCH/$TRAVIS_COMMIT/"; fi
  - if [[ $HUGO_ENV == "production" ]]; then hugo; fi

before_deploy:
  - make public/ci.json
  - sed -i -e "s/123456abcdef/$TRAVIS_COMMIT/" public/index.html

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: public/
    bucket: "laps.run"
    skip_cleanup: true
    on:
      repo: tphummel/laps.run
      branch: master
      condition: "$HUGO_ENV == production"
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: public/
    bucket: "laps.run-preview"
    skip_cleanup: true
    on:
      repo: tphummel/laps.run
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"
