baseurl       = "https://laps.run/"
languagecode  = "en-us"
title         = "Running Venues"
uglyurls      = false
# disableKinds  = ["section"]

[taxonomies]
  tag = "tags"
  surface_type = "surface_types"


[params]
    Title = "Running Venues"

[mediaTypes]
  [mediaTypes."text/csv"]
    suffix = "csv"

[outputs]
  section = ["HTML", "RSS", "CSV"]
