baseurl       = "https://laps.run/"
languagecode  = "en-us"
title         = "Running Venues"
uglyurls      = false
# disableKinds  = ["section"]

[taxonomies]
  tag = "tags"

[params]
    Title = "Running Venues"
    google_maps_token = "AIzaSyAinDLEEbcSxJe9EUMSJe1nOpN_zOiPDDk"

[mediaTypes]
  [mediaTypes."text/csv"]
    suffixes = ["csv"]

[outputs]
  section = ["HTML", "RSS", "CSV"]
